#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Initializing a counter
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
    # Incrementing the counter
    ((counter++))
    
    # Using if statement to check if it's the 9th iteration
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
done
